# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '2-4-3' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for 2-4-3
  pod 'AFNetworking'
  target '2-4-3Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '2-4-3UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
